name: Windows

on:
  push:
    branches:
      - master
      - feature/fix-builds
  pull_request:
    branches:
      - master

env:
  BUILD_TYPE: Release

jobs:
  build:

    runs-on: windows-latest
    
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v1
    - uses: msys2/setup-msys2@v2
      with:
          msystem: MINGW64
          update: true

    - name: Install dependencies
      run: pacman -Sq --noconfirm git pkgconf mingw-w64-x86_64-{cmake,SDL2,qt6-static,qt6-base,qt6-multimedia,libarchive,toolchain}

    - name: Configure
      working-directory: ${{runner.workspace}}
      run: cmake -B build $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_STATIC=OFF -DUSE_QT6=ON

    - name: Make
      working-directory: ${{runner.workspace}}/build
      run: |
        cmake --build .
    
    - name: Preparing artifacts
      working-directory: ${{runner.workspace}}/build
      run: |
        mkdir dist
        mkdir -p ./dist/roms
        touch ./dist/roms/DELETE_ME
        mkdir -p ./dist/assets/days/cutscenes/cinematics
        touch ./dist/assets/days/cutscenes/cinematics/DELETE_ME
        mv melonDS.exe ./dist/MelonMix.exe
        cp D:/a/_temp/msys64/mingw64/bin/*.dll ./dist/
        cp -r D:/a/_temp/msys64/mingw64/share/qt6/plugins/platforms ./dist/platforms/
        cp -r D:/a/_temp/msys64/mingw64/share/qt6/plugins/multimedia ./dist/multimedia/
        cp ../scripts/MelonMix_KHDays.bat    ./dist/MelonMix_KHDays.bat
        cp ../scripts/MelonMix_KHReCoded.bat ./dist/MelonMix_KHReCoded.bat

    - uses: actions/upload-artifact@v4
      with:
        name: MelonMix-windows-x86_64
        path: ${{runner.workspace}}\build\dist
