name: Windows

on:
  push:
    branches:
      - master
      - ci/*
  pull_request:
    branches:
      - master

env:
  MELONDS_GIT_BRANCH: ${{ github.ref }}
  MELONDS_GIT_HASH: ${{ github.sha }}
  MELONDS_BUILD_PROVIDER: GitHub Actions

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Check out sources
      uses: actions/checkout@v3
    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: ucrt64
        update: true
        pacboy: gcc:p cmake:p ninja:p make:p
    - name: Set up vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: 10b7a178346f3f0abef60cecd5130e295afd8da4
    - name: Configure
      run: cmake --preset=release-mingw-x86_64 -DMELONDS_EMBED_BUILD_INFO=ON
    - name: Build
      run: cmake --build --preset=release-mingw-x86_64
    - name: Preparing artifacts
      run: |
        ls
        cd build
        mkdir dist
        mkdir -p ./dist/roms
        touch ./dist/roms/DELETE_ME
        mkdir -p ./dist/assets/days/cutscenes/cinematics
        touch ./dist/assets/days/cutscenes/cinematics/DELETE_ME
        mv ./release-mingw-x86_64/melonDS.exe ./dist/MelonMix.exe
        cp D:/a/_temp/msys64/mingw64/bin/*.dll ./dist/
        cp -r D:/a/_temp/msys64/mingw64/share/qt6/plugins/platforms ./dist/platforms/
        cp -r D:/a/_temp/msys64/mingw64/share/qt6/plugins/multimedia ./dist/multimedia/
        cp ../KHMelonMix/res/scripts/MelonMix_KHDays.bat    ./dist/MelonMix_KHDays.bat
        cp ../KHMelonMix/res/scripts/MelonMix_KHReCoded.bat ./dist/MelonMix_KHReCoded.bat

    - uses: actions/upload-artifact@v4
      with:
        name: MelonMix-windows-x86_64
        path: ${{runner.workspace}}\build\dist
